module.exports = {
    registerUser: require('./user-register'),
    authenticateUser: require('./user-authenticate'),
    retrieveUser: require('./user-retrieve'),
    createCompany: require('./company-create'),
    companyRetrieve: require('./company-retrieve'),
    companyUpdate: require('./company-update'),
    companyDelete: require('./company-delete'),
    workerRegister: require('./worker-register'),
    weekDaysCreate: require('./week-days-create'),
    weekDaysRetrieve: require('./week-days-retrieve'),
    weekDaysUpdate: require('./week-days-update'),
    eventCreate: require('./event-create'),
    eventCompanyCreate: require('./event-company-create'),
    eventSignInOut: require('./event-sign-in-out'),
    clientCompanyCreate: require('./client-company-create'),
    eventCompanyRetrieve: require('./event-company-retrieve'),
    eventsRetrieve: require('./events-retrieve'),
    dashboardAnalytics: require('./dashboard-analytics'),
    sendInviteLink: require('./send-invite-link'),
    eventUpdate: require('./event-update'),
    eventDelete: require('./event-delete'),
}